### ISSUE TITLE
Older versions of sven_internal.dll will not run with the newest version of svenmod

### ISSUE THREAD

**Issue by Taklaminon** [sw1ft747/svenmod#4]
When attempting to open an older version of sven_internal.dll, the loader returns the error: 

[SvenMod] Could not get "IClientPlugin" interface from the plugin "sven_internal"
[SvenMod] The plugin "sven_internal" may have a newer version of the interface. In this case, get updated version of SvenMod here: https://github.com/sw1ft747/svenmod

I imagine this issue extends to other plugins, which is a pretty big problem considering how old most sven plugins are.

**Comment by sw1ft747** [comment]
svenint isn't supported anymore, all other plugins are up to date with svenmod
